"""empty message

Revision ID: 659838242f20
Revises: 622970cb8c15
Create Date: 2021-05-23 17:32:34.467985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659838242f20'
down_revision = '622970cb8c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrega')
    # ### end Alembic commands ###
